# Generated by Django 2.2.6 on 2019-10-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20191025_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer',
        ),
    ]
