# Generated by Django 2.2.6 on 2019-10-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profiles Manager', 'verbose_name_plural': 'Profiles Manager'},
        ),
    ]
