# Generated by Django 2.2.6 on 2019-10-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Question Manager', 'verbose_name_plural': 'Questions Manager'},
        ),
    ]
