# Generated by Django 2.2.6 on 2019-10-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='status',
            new_name='active',
        ),
    ]
