# Generated by Django 2.2.6 on 2019-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20191023_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
